###########################################################
# GYRO TEMPLATES
###########################################################

#######################################
# NavX
#######################################

[gyro-templates.navx]

#######################################
# Pigeon
#######################################

[gyro-templates.pigeon]

###########################################################
# SENSOR TEMPLATES
###########################################################

#######################################
# PWM Absolute Encoder on a Canifier
#######################################

[sensor-templates.canified-pwm]
inverted = false
ratio = 1
offset = 0

#######################################
# CANCoder
#######################################

[sensor-templates.cancoder]
inverted = false
ratio = 1
offset = 0

###########################################################
# MOTOR TEMPLATES
###########################################################

#######################################
# Falcon500
#######################################

[motor-templates.falcon500]
inverted = false
max-speed-rps = 101.0

#######################################
# Neo
#######################################

[motor-templates.neo]
inverted = false
max-speed-rps = 90.0



###########################################################
# MODULE TEMPLATES
###########################################################

#######################################
# Team 88 Diff Swerve 2021 (beta)
#######################################

[module-templates.team88.diff-swerve-2021.beta]
differential-matrix = [
        [0.041666666, -0.041666666],
        [0.069444444, 0.09722222]
    ]
wheel-diameter-inches = 3.5
motor-0-name = "lo"
motor-1-name = "hi"
azimuth-sensor.template = "cancoder"
azimuth-sensor.ratio = 0.0027778

[module-templates.team88.diff-swerve-2021.beta.motors.hi]
template = "falcon500"

[module-templates.team88.diff-swerve-2021.beta.motors.lo]
template = "falcon500"

[module-templates.team88.diff-swerve-2021.beta.azimuth-controller]
kP = 20.0
kI = 0.0
kD = 10.0
kF = 0.0
i-zone = 0.0
i-max = 0.0
max-speed = 1440
max-acceleration = 1080

[module-templates.team88.diff-swerve-2021.beta.wheel-controller]
kP = 0.0
kI = 0.1
kD = 0.5
i-zone = 1.5
i-max = 0.0
