name: Deploy to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Maven-Deployment
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Publish to staging
        run: gradle publishToSonatype
        env:
          SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      - name: Deploy to Maven Central
        run: gradle closeAndReleaseSonatypeStagingRepository
        env:
          SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_TOKEN }}